name: Test
on:
  push:
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+.*", "trigger-push"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [ '1.20', '1.17' ]
        platform: [ ubuntu-22.04, macos-13, windows-2019 ]
    runs-on: ${{ matrix.platform }}
    if: always()

    steps:
      - name: Install Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout repository
        uses: actions/checkout@v3.6.0
      - name: Test
        shell: bash
        run: |
          go test -v -covermode=atomic -coverprofile "coverage.cov" ./...
          go tool cover -func="coverage.cov"
          go tool cover -html="coverage.cov" -o "coverage.html"
